# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python package

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'
    - name: Install package
      run: |
        python -m pip install --upgrade pip flake8
        pip install -r requirements.txt
        pip install .
    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    - name: Test with pytest
      run: |
        dask-gateway-server generate-config
        python tests/set_gateway_config.py
        dask-gateway-server -f dask_gateway_config.py &
        pytest
        rm -f docs/rhg_compute_tools.*.rst
        sphinx-apidoc -o docs rhg_compute_tools
        sphinx-build -W -b html -d docs/_build/doctrees docs/. docs/_build/html
        python setup.py sdist bdist_wheel
        twine check dist/rhg_compute_tools-*.tar.gz
        python setup.py clean
